default: &default
  adapter: postgresql
  encoding: unicode
  database: wedstival
  pool: 5
  username: wedstival
  password:

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default

development:
  <<: *default
